addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 5481ad3d-d39f-4987-ba87-8d28a379dc87
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  ~/.m2/settings.xml
branches: ''
cache:
  directories:
  - $HOME/.m2
  - download
  - $HOME/.m2
env:
  matrix:
  - PROFILE=ci
  - PROFILE=spring41-next
  - PROFILE=spring42
  - PROFILE=spring42-next
  - PROFILE=spring43
  - PROFILE=spring43-next
  - PROFILE=spring5-next
  - PROFILE=external-cassandra CASSANDRA_VERSION=2.2.6
  - PROFILE=external-cassandra CASSANDRA_VERSION=3.0.7
  - PROFILE=external-cassandra CASSANDRA_VERSION=3.2
  - PROFILE=external-cassandra CASSANDRA_VERSION=3.3
  - PROFILE=external-cassandra CASSANDRA_VERSION=3.4
  - PROFILE=external-cassandra CASSANDRA_VERSION=3.5
  - PROFILE=external-cassandra CASSANDRA_VERSION=3.6
  - PROFILE=external-cassandra CASSANDRA_VERSION=3.7
install: if [ ! -z ${CASSANDRA_VERSION} ]; then ./setup-cassandra.sh; fi;
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=5481ad3d-d39f-4987-ba87-8d28a379dc87
script:
- mvn clean install -P${PROFILE} -Dmaven.javadoc.skip=true
sudo: false
# Modified by Insights Service at 2017-01-02 07:30:20.576634
